//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D4Companion.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D4Companion.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix.
        /// </summary>
        internal static string rsCapAffix {
            get {
                return ResourceManager.GetString("rsCapAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affixes.
        /// </summary>
        internal static string rsCapAffixes {
            get {
                return ResourceManager.GetString("rsCapAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        internal static string rsCapAmulet {
            get {
                return ResourceManager.GetString("rsCapAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings.
        /// </summary>
        internal static string rsCapAppsettings {
            get {
                return ResourceManager.GetString("rsCapAppsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspects.
        /// </summary>
        internal static string rsCapAspects {
            get {
                return ResourceManager.GetString("rsCapAspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Images.
        /// </summary>
        internal static string rsCapAvailableImages {
            get {
                return ResourceManager.GetString("rsCapAvailableImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available system presets:.
        /// </summary>
        internal static string rsCapAvailableSystemPresets {
            get {
                return ResourceManager.GetString("rsCapAvailableSystemPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string rsCapBarbarian {
            get {
                return ResourceManager.GetString("rsCapBarbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string rsCapBoots {
            get {
                return ResourceManager.GetString("rsCapBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Threshold:.
        /// </summary>
        internal static string rsCapBrightnessThreshold {
            get {
                return ResourceManager.GetString("rsCapBrightnessThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caged Hearts.
        /// </summary>
        internal static string rsCapCagedHearts {
            get {
                return ResourceManager.GetString("rsCapCagedHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string rsCapCheckforUpdates {
            get {
                return ResourceManager.GetString("rsCapCheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string rsCapChest {
            get {
                return ResourceManager.GetString("rsCapChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        internal static string rsCapClearLog {
            get {
                return ResourceManager.GetString("rsCapClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config: .
        /// </summary>
        internal static string rsCapConfig {
            get {
                return ResourceManager.GetString("rsCapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm name.
        /// </summary>
        internal static string rsCapConfirmName {
            get {
                return ResourceManager.GetString("rsCapConfirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumables.
        /// </summary>
        internal static string rsCapConsumables {
            get {
                return ResourceManager.GetString("rsCapConsumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Mode.
        /// </summary>
        internal static string rsCapControllerMode {
            get {
                return ResourceManager.GetString("rsCapControllerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string rsCapCore {
            get {
                return ResourceManager.GetString("rsCapCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D4Builds.
        /// </summary>
        internal static string rsCapD4Builds {
            get {
                return ResourceManager.GetString("rsCapD4Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string rsCapDebug {
            get {
                return ResourceManager.GetString("rsCapDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        internal static string rsCapDebugMode {
            get {
                return ResourceManager.GetString("rsCapDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string rsCapDescription {
            get {
                return ResourceManager.GetString("rsCapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string rsCapDone {
            get {
                return ResourceManager.GetString("rsCapDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading. Please wait..
        /// </summary>
        internal static string rsCapDownloadingWait {
            get {
                return ResourceManager.GetString("rsCapDownloadingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string rsCapDruid {
            get {
                return ResourceManager.GetString("rsCapDruid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        internal static string rsCapDungeons {
            get {
                return ResourceManager.GetString("rsCapDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elixers.
        /// </summary>
        internal static string rsCapElixers {
            get {
                return ResourceManager.GetString("rsCapElixers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental features:.
        /// </summary>
        internal static string rsCapExperimentalfeatures {
            get {
                return ResourceManager.GetString("rsCapExperimentalfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name: .
        /// </summary>
        internal static string rsCapFileName {
            get {
                return ResourceManager.GetString("rsCapFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Affix Presets:.
        /// </summary>
        internal static string rsCapGearAffixPresets {
            get {
                return ResourceManager.GetString("rsCapGearAffixPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        internal static string rsCapGloves {
            get {
                return ResourceManager.GetString("rsCapGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm.
        /// </summary>
        internal static string rsCapHelm {
            get {
                return ResourceManager.GetString("rsCapHelm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys:.
        /// </summary>
        internal static string rsCapHotkeys {
            get {
                return ResourceManager.GetString("rsCapHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game Overlay Config:.
        /// </summary>
        internal static string rsCapInGameOverlayConfig {
            get {
                return ResourceManager.GetString("rsCapInGameOverlayConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes.
        /// </summary>
        internal static string rsCapItemAffixes {
            get {
                return ResourceManager.GetString("rsCapItemAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes Areas.
        /// </summary>
        internal static string rsCapItemAffixesAreas {
            get {
                return ResourceManager.GetString("rsCapItemAffixesAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes Locations.
        /// </summary>
        internal static string rsCapItemAffixesLocations {
            get {
                return ResourceManager.GetString("rsCapItemAffixesLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect.
        /// </summary>
        internal static string rsCapItemAspect {
            get {
                return ResourceManager.GetString("rsCapItemAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect Area.
        /// </summary>
        internal static string rsCapItemAspectArea {
            get {
                return ResourceManager.GetString("rsCapItemAspectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect Location.
        /// </summary>
        internal static string rsCapItemAspectLocation {
            get {
                return ResourceManager.GetString("rsCapItemAspectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Socket Locations.
        /// </summary>
        internal static string rsCapItemSocketLocations {
            get {
                return ResourceManager.GetString("rsCapItemSocketLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tooltip.
        /// </summary>
        internal static string rsCapItemTooltip {
            get {
                return ResourceManager.GetString("rsCapItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string rsCapItemType {
            get {
                return ResourceManager.GetString("rsCapItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        internal static string rsCapKey {
            get {
                return ResourceManager.GetString("rsCapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string rsCapLanguage {
            get {
                return ResourceManager.GetString("rsCapLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string rsCapLocal {
            get {
                return ResourceManager.GetString("rsCapLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string rsCapLogging {
            get {
                return ResourceManager.GetString("rsCapLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string rsCapMajor {
            get {
                return ResourceManager.GetString("rsCapMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers.
        /// </summary>
        internal static string rsCapMarkers {
            get {
                return ResourceManager.GetString("rsCapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxroll.
        /// </summary>
        internal static string rsCapMaxroll {
            get {
                return ResourceManager.GetString("rsCapMaxroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        internal static string rsCapMinor {
            get {
                return ResourceManager.GetString("rsCapMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier:.
        /// </summary>
        internal static string rsCapModifier {
            get {
                return ResourceManager.GetString("rsCapModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        internal static string rsCapNecromancer {
            get {
                return ResourceManager.GetString("rsCapNecromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented..
        /// </summary>
        internal static string rsCapNotYetImplemented {
            get {
                return ResourceManager.GetString("rsCapNotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Results.
        /// </summary>
        internal static string rsCapOcrResults {
            get {
                return ResourceManager.GetString("rsCapOcrResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offhand.
        /// </summary>
        internal static string rsCapOffhand {
            get {
                return ResourceManager.GetString("rsCapOffhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string rsCapOverlay {
            get {
                return ResourceManager.GetString("rsCapOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string rsCapOverlayFontSize {
            get {
                return ResourceManager.GetString("rsCapOverlayFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Icon Location.
        /// </summary>
        internal static string rsCapOverlayIconLocation {
            get {
                return ResourceManager.GetString("rsCapOverlayIconLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        internal static string rsCapPants {
            get {
                return ResourceManager.GetString("rsCapPants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        internal static string rsCapPositive {
            get {
                return ResourceManager.GetString("rsCapPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string rsCapRanged {
            get {
                return ResourceManager.GetString("rsCapRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution: .
        /// </summary>
        internal static string rsCapResolution {
            get {
                return ResourceManager.GetString("rsCapResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string rsCapRing {
            get {
                return ResourceManager.GetString("rsCapRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string rsCapRogue {
            get {
                return ResourceManager.GetString("rsCapRogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        internal static string rsCapSeasonal {
            get {
                return ResourceManager.GetString("rsCapSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string rsCapSettings {
            get {
                return ResourceManager.GetString("rsCapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigils.
        /// </summary>
        internal static string rsCapSigils {
            get {
                return ResourceManager.GetString("rsCapSigils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Affix):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAffix {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Affix location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAffixlocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAffixlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Aspect):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAspect {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Aspect location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAspectlocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAspectlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Socket location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdSocketlocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdSocketlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Tooltip):.
        /// </summary>
        internal static string rsCapSimilarityThresholdTooltip {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Type):.
        /// </summary>
        internal static string rsCapSimilarityThresholdType {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        internal static string rsCapSorcerer {
            get {
                return ResourceManager.GetString("rsCapSorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Preset.
        /// </summary>
        internal static string rsCapSwitchPreset {
            get {
                return ResourceManager.GetString("rsCapSwitchPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System presets:.
        /// </summary>
        internal static string rsCapSystempresets {
            get {
                return ResourceManager.GetString("rsCapSystempresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Overlay.
        /// </summary>
        internal static string rsCapToggleOverlay {
            get {
                return ResourceManager.GetString("rsCapToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip width:.
        /// </summary>
        internal static string rsCapTooltipWidth {
            get {
                return ResourceManager.GetString("rsCapTooltipWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string rsCapWeapon {
            get {
                return ResourceManager.GetString("rsCapWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset {0} activated..
        /// </summary>
        internal static string rsFormatPresetActivated {
            get {
                return ResourceManager.GetString("rsFormatPresetActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string rsTooltipAdd {
            get {
                return ResourceManager.GetString("rsTooltipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add D4Builds Build.
        /// </summary>
        internal static string rsTooltipAddD4BuildsBuild {
            get {
                return ResourceManager.GetString("rsTooltipAddD4BuildsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maxroll Build.
        /// </summary>
        internal static string rsTooltipAddMaxrollBuild {
            get {
                return ResourceManager.GetString("rsTooltipAddMaxrollBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add preset.
        /// </summary>
        internal static string rsTooltipAddPreset {
            get {
                return ResourceManager.GetString("rsTooltipAddPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates at startup..
        /// </summary>
        internal static string rsTooltipCheckforUpdates {
            get {
                return ResourceManager.GetString("rsTooltipCheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to use a controller instead of a mouse. Warning: This method is 70+ ms slower..
        /// </summary>
        internal static string rsTooltipControllerMode {
            get {
                return ResourceManager.GetString("rsTooltipControllerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the build id from the D4Builds website and click the add button. The build id is the last part of the url. For example: 660881f7-cb6a-4162-be62-29f0afeb37bf..
        /// </summary>
        internal static string rsTooltipD4BuildsImportHelp {
            get {
                return ResourceManager.GetString("rsTooltipD4BuildsImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit D4Builds.gg.
        /// </summary>
        internal static string rsTooltipD4BuildsWeb {
            get {
                return ResourceManager.GetString("rsTooltipD4BuildsWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test template matching without running Diablo IV..
        /// </summary>
        internal static string rsTooltipDebugMode {
            get {
                return ResourceManager.GetString("rsTooltipDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop only.
        /// </summary>
        internal static string rsTooltipDropOnly {
            get {
                return ResourceManager.GetString("rsTooltipDropOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable consumable item type filtering..
        /// </summary>
        internal static string rsTooltipEnableConsumable {
            get {
                return ResourceManager.GetString("rsTooltipEnableConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable seasonal item type filtering..
        /// </summary>
        internal static string rsTooltipEnableSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipEnableSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export preset.
        /// </summary>
        internal static string rsTooltipExportPreset {
            get {
                return ResourceManager.GetString("rsTooltipExportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D4 Companion on GitHub.
        /// </summary>
        internal static string rsToolTipGitHub {
            get {
                return ResourceManager.GetString("rsToolTipGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki on GitHub.
        /// </summary>
        internal static string rsToolTipGitHubWiki {
            get {
                return ResourceManager.GetString("rsToolTipGitHubWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import preset.
        /// </summary>
        internal static string rsTooltipImportPreset {
            get {
                return ResourceManager.GetString("rsTooltipImportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Ko-fi.
        /// </summary>
        internal static string rsToolTipKoFi {
            get {
                return ResourceManager.GetString("rsToolTipKoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the overlay marker style..
        /// </summary>
        internal static string rsTooltipMarkerStyle {
            get {
                return ResourceManager.GetString("rsTooltipMarkerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the build id from the Maxroll website and click the add button. The build id is the last part of the url. For example: t3jx0916.
        /// </summary>
        internal static string rsTooltipMaxrollImportHelp {
            get {
                return ResourceManager.GetString("rsTooltipMaxrollImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Maxroll.com.
        /// </summary>
        internal static string rsTooltipMaxrollWeb {
            get {
                return ResourceManager.GetString("rsTooltipMaxrollWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s).
        /// </summary>
        internal static string rsTooltipMissingItemType {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) amulet_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeAmulet {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) boots_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeBoots {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) chest_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeChest {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) consumable_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeConsumable {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) gloves_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeGloves {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) helm_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeHelm {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeHelm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) offhand_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeOffhand {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeOffhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) pants_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypePants {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypePants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) ranged_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeRanged {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) ring_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeRing {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) seasonal_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) sigil_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeSigil {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeSigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing item type image(s) weapon_*.png.
        /// </summary>
        internal static string rsTooltipMissingItemTypeWeapon {
            get {
                return ResourceManager.GetString("rsTooltipMissingItemTypeWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the font size of overlay messages..
        /// </summary>
        internal static string rsTooltipOverlayFontSize {
            get {
                return ResourceManager.GetString("rsTooltipOverlayFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the location of the onscreen overlay icon while active..
        /// </summary>
        internal static string rsTooltipOverlayIconLocation {
            get {
                return ResourceManager.GetString("rsTooltipOverlayIconLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the preset matching your configuration and follow the recommended app settings. If the button is disabled turn off the overlay first..
        /// </summary>
        internal static string rsTooltipPresetDownloadTip {
            get {
                return ResourceManager.GetString("rsTooltipPresetDownloadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string rsTooltipRemove {
            get {
                return ResourceManager.GetString("rsTooltipRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove preset.
        /// </summary>
        internal static string rsTooltipRemovePreset {
            get {
                return ResourceManager.GetString("rsTooltipRemovePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        internal static string rsTooltipSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set affix.
        /// </summary>
        internal static string rsTooltipSetAffix {
            get {
                return ResourceManager.GetString("rsTooltipSetAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set aspect.
        /// </summary>
        internal static string rsTooltipSetAspect {
            get {
                return ResourceManager.GetString("rsTooltipSetAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set controller images..
        /// </summary>
        internal static string rsTooltipSetControllerImages {
            get {
                return ResourceManager.GetString("rsTooltipSetControllerImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set sigil.
        /// </summary>
        internal static string rsTooltipSetSigil {
            get {
                return ResourceManager.GetString("rsTooltipSetSigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a blacklist allows you to add all sigil affixes you do not want..
        /// </summary>
        internal static string rsTooltipSigilModes {
            get {
                return ResourceManager.GetString("rsTooltipSigilModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle through available affix presets..
        /// </summary>
        internal static string rsTooltipSwitchPreset {
            get {
                return ResourceManager.GetString("rsTooltipSwitchPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the overlay on/off..
        /// </summary>
        internal static string rsTooltipToggleOverlay {
            get {
                return ResourceManager.GetString("rsTooltipToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string rsTooltipUpdate {
            get {
                return ResourceManager.GetString("rsTooltipUpdate", resourceCulture);
            }
        }
    }
}
