//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D4Companion.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D4Companion.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix.
        /// </summary>
        internal static string rsCapAffix {
            get {
                return ResourceManager.GetString("rsCapAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix Area Height Offset (Bottom):.
        /// </summary>
        internal static string rsCapAffixAreaHeightOffsetBottom {
            get {
                return ResourceManager.GetString("rsCapAffixAreaHeightOffsetBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix Area Height Offset (Top):.
        /// </summary>
        internal static string rsCapAffixAreaHeightOffsetTop {
            get {
                return ResourceManager.GetString("rsCapAffixAreaHeightOffsetTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix/Aspect Area Width Offset:.
        /// </summary>
        internal static string rsCapAffixAspectAreaWidthOffset {
            get {
                return ResourceManager.GetString("rsCapAffixAspectAreaWidthOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affixes.
        /// </summary>
        internal static string rsCapAffixes {
            get {
                return ResourceManager.GetString("rsCapAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        internal static string rsCapAmulet {
            get {
                return ResourceManager.GetString("rsCapAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Type.
        /// </summary>
        internal static string rsCapAnyType {
            get {
                return ResourceManager.GetString("rsCapAnyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings.
        /// </summary>
        internal static string rsCapAppsettings {
            get {
                return ResourceManager.GetString("rsCapAppsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Area Height Offset (Top):.
        /// </summary>
        internal static string rsCapAspectAreaHeightOffsetTop {
            get {
                return ResourceManager.GetString("rsCapAspectAreaHeightOffsetTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Detection.
        /// </summary>
        internal static string rsCapAspectDetection {
            get {
                return ResourceManager.GetString("rsCapAspectDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Results (Aspect).
        /// </summary>
        internal static string rsCapAspectOcrResults {
            get {
                return ResourceManager.GetString("rsCapAspectOcrResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspects.
        /// </summary>
        internal static string rsCapAspects {
            get {
                return ResourceManager.GetString("rsCapAspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Images.
        /// </summary>
        internal static string rsCapAvailableImages {
            get {
                return ResourceManager.GetString("rsCapAvailableImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available system presets:.
        /// </summary>
        internal static string rsCapAvailableSystemPresets {
            get {
                return ResourceManager.GetString("rsCapAvailableSystemPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string rsCapBarbarian {
            get {
                return ResourceManager.GetString("rsCapBarbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string rsCapBoots {
            get {
                return ResourceManager.GetString("rsCapBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Threshold:.
        /// </summary>
        internal static string rsCapBrightnessThreshold {
            get {
                return ResourceManager.GetString("rsCapBrightnessThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build 1.
        /// </summary>
        internal static string rsCapBuild1 {
            get {
                return ResourceManager.GetString("rsCapBuild1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build 1+2.
        /// </summary>
        internal static string rsCapBuild12 {
            get {
                return ResourceManager.GetString("rsCapBuild12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build 2.
        /// </summary>
        internal static string rsCapBuild2 {
            get {
                return ResourceManager.GetString("rsCapBuild2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caged Hearts.
        /// </summary>
        internal static string rsCapCagedHearts {
            get {
                return ResourceManager.GetString("rsCapCagedHearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string rsCapCancel {
            get {
                return ResourceManager.GetString("rsCapCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string rsCapCheckforUpdates {
            get {
                return ResourceManager.GetString("rsCapCheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string rsCapChest {
            get {
                return ResourceManager.GetString("rsCapChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        internal static string rsCapChineseSimplified {
            get {
                return ResourceManager.GetString("rsCapChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        internal static string rsCapChineseTraditional {
            get {
                return ResourceManager.GetString("rsCapChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        internal static string rsCapClearLog {
            get {
                return ResourceManager.GetString("rsCapClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config: .
        /// </summary>
        internal static string rsCapConfig {
            get {
                return ResourceManager.GetString("rsCapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm name.
        /// </summary>
        internal static string rsCapConfirmName {
            get {
                return ResourceManager.GetString("rsCapConfirmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumables.
        /// </summary>
        internal static string rsCapConsumables {
            get {
                return ResourceManager.GetString("rsCapConsumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Mode.
        /// </summary>
        internal static string rsCapControllerMode {
            get {
                return ResourceManager.GetString("rsCapControllerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        internal static string rsCapCore {
            get {
                return ResourceManager.GetString("rsCapCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Item.
        /// </summary>
        internal static string rsCapCurrentItem {
            get {
                return ResourceManager.GetString("rsCapCurrentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 D4Builds.
        /// </summary>
        internal static string rsCapD4Builds {
            get {
                return ResourceManager.GetString("rsCapD4Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string rsCapDebug {
            get {
                return ResourceManager.GetString("rsCapDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        internal static string rsCapDebugMode {
            get {
                return ResourceManager.GetString("rsCapDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string rsCapDescription {
            get {
                return ResourceManager.GetString("rsCapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string rsCapDone {
            get {
                return ResourceManager.GetString("rsCapDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading. Please wait..
        /// </summary>
        internal static string rsCapDownloadingWait {
            get {
                return ResourceManager.GetString("rsCapDownloadingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string rsCapDruid {
            get {
                return ResourceManager.GetString("rsCapDruid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        internal static string rsCapDungeons {
            get {
                return ResourceManager.GetString("rsCapDungeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon Tiers.
        /// </summary>
        internal static string rsCapDungeonTiers {
            get {
                return ResourceManager.GetString("rsCapDungeonTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elixers.
        /// </summary>
        internal static string rsCapElixers {
            get {
                return ResourceManager.GetString("rsCapElixers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string rsCapEnglish {
            get {
                return ResourceManager.GetString("rsCapEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental features:.
        /// </summary>
        internal static string rsCapExperimentalfeatures {
            get {
                return ResourceManager.GetString("rsCapExperimentalfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string rsCapFeatures {
            get {
                return ResourceManager.GetString("rsCapFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name: .
        /// </summary>
        internal static string rsCapFileName {
            get {
                return ResourceManager.GetString("rsCapFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string rsCapFrench {
            get {
                return ResourceManager.GetString("rsCapFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Affix Presets:.
        /// </summary>
        internal static string rsCapGearAffixPresets {
            get {
                return ResourceManager.GetString("rsCapGearAffixPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string rsCapGeneral {
            get {
                return ResourceManager.GetString("rsCapGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string rsCapGerman {
            get {
                return ResourceManager.GetString("rsCapGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        internal static string rsCapGloves {
            get {
                return ResourceManager.GetString("rsCapGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater.
        /// </summary>
        internal static string rsCapGreater {
            get {
                return ResourceManager.GetString("rsCapGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm.
        /// </summary>
        internal static string rsCapHelm {
            get {
                return ResourceManager.GetString("rsCapHelm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Hotkeys.
        /// </summary>
        internal static string rsCapHotkeys {
            get {
                return ResourceManager.GetString("rsCapHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string rsCapId {
            get {
                return ResourceManager.GetString("rsCapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit.
        /// </summary>
        internal static string rsCapImplicit {
            get {
                return ResourceManager.GetString("rsCapImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import paragon boards.
        /// </summary>
        internal static string rsCapImportParagon {
            get {
                return ResourceManager.GetString("rsCapImportParagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import preset.
        /// </summary>
        internal static string rsCapImportPreset {
            get {
                return ResourceManager.GetString("rsCapImportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include unique affixes.
        /// </summary>
        internal static string rsCapImportUniqueAffixes {
            get {
                return ResourceManager.GetString("rsCapImportUniqueAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game Overlay Config:.
        /// </summary>
        internal static string rsCapInGameOverlayConfig {
            get {
                return ResourceManager.GetString("rsCapInGameOverlayConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string rsCapItalian {
            get {
                return ResourceManager.GetString("rsCapItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes.
        /// </summary>
        internal static string rsCapItemAffixes {
            get {
                return ResourceManager.GetString("rsCapItemAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes Areas.
        /// </summary>
        internal static string rsCapItemAffixesAreas {
            get {
                return ResourceManager.GetString("rsCapItemAffixesAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Affixes Locations.
        /// </summary>
        internal static string rsCapItemAffixesLocations {
            get {
                return ResourceManager.GetString("rsCapItemAffixesLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect.
        /// </summary>
        internal static string rsCapItemAspect {
            get {
                return ResourceManager.GetString("rsCapItemAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect Area.
        /// </summary>
        internal static string rsCapItemAspectArea {
            get {
                return ResourceManager.GetString("rsCapItemAspectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Aspect Location.
        /// </summary>
        internal static string rsCapItemAspectLocation {
            get {
                return ResourceManager.GetString("rsCapItemAspectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Power Limit.
        /// </summary>
        internal static string rsCapItemPowerLimit {
            get {
                return ResourceManager.GetString("rsCapItemPowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Socket Locations.
        /// </summary>
        internal static string rsCapItemSocketLocations {
            get {
                return ResourceManager.GetString("rsCapItemSocketLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Splitter Locations.
        /// </summary>
        internal static string rsCapItemSplitterLocations {
            get {
                return ResourceManager.GetString("rsCapItemSplitterLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tooltip.
        /// </summary>
        internal static string rsCapItemTooltip {
            get {
                return ResourceManager.GetString("rsCapItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string rsCapItemType {
            get {
                return ResourceManager.GetString("rsCapItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Results (ItemType + Power).
        /// </summary>
        internal static string rsCapItemTypePowerOcrResults {
            get {
                return ResourceManager.GetString("rsCapItemTypePowerOcrResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string rsCapJapanese {
            get {
                return ResourceManager.GetString("rsCapJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        internal static string rsCapKey {
            get {
                return ResourceManager.GetString("rsCapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string rsCapKorean {
            get {
                return ResourceManager.GetString("rsCapKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string rsCapLanguage {
            get {
                return ResourceManager.GetString("rsCapLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Offset (Collapsed).
        /// </summary>
        internal static string rsCapLeftOffsetCollapsed {
            get {
                return ResourceManager.GetString("rsCapLeftOffsetCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string rsCapLocal {
            get {
                return ResourceManager.GetString("rsCapLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string rsCapLogging {
            get {
                return ResourceManager.GetString("rsCapLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string rsCapMajor {
            get {
                return ResourceManager.GetString("rsCapMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Colors.
        /// </summary>
        internal static string rsCapManageColors {
            get {
                return ResourceManager.GetString("rsCapManageColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers.
        /// </summary>
        internal static string rsCapMarkers {
            get {
                return ResourceManager.GetString("rsCapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Maxroll.
        /// </summary>
        internal static string rsCapMaxroll {
            get {
                return ResourceManager.GetString("rsCapMaxroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string rsCapMerge {
            get {
                return ResourceManager.GetString("rsCapMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Affix Value.
        /// </summary>
        internal static string rsCapMinimalAffixValue {
            get {
                return ResourceManager.GetString("rsCapMinimalAffixValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Affix Value Filter.
        /// </summary>
        internal static string rsCapMinimalAffixValueFilter {
            get {
                return ResourceManager.GetString("rsCapMinimalAffixValueFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal OCR Match (Type):.
        /// </summary>
        internal static string rsCapMinimalOcrMatchType {
            get {
                return ResourceManager.GetString("rsCapMinimalOcrMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor.
        /// </summary>
        internal static string rsCapMinor {
            get {
                return ResourceManager.GetString("rsCapMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 Mobalytics.
        /// </summary>
        internal static string rsCapMobalytics {
            get {
                return ResourceManager.GetString("rsCapMobalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier:.
        /// </summary>
        internal static string rsCapModifier {
            get {
                return ResourceManager.GetString("rsCapModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Build Mode.
        /// </summary>
        internal static string rsCapMultiBuildMode {
            get {
                return ResourceManager.GetString("rsCapMultiBuildMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        internal static string rsCapNecromancer {
            get {
                return ResourceManager.GetString("rsCapNecromancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string rsCapNormal {
            get {
                return ResourceManager.GetString("rsCapNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented..
        /// </summary>
        internal static string rsCapNotYetImplemented {
            get {
                return ResourceManager.GetString("rsCapNotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        internal static string rsCapOCR {
            get {
                return ResourceManager.GetString("rsCapOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Clean.
        /// </summary>
        internal static string rsCapOCRClean {
            get {
                return ResourceManager.GetString("rsCapOCRClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Results (Affixes).
        /// </summary>
        internal static string rsCapOcrResults {
            get {
                return ResourceManager.GetString("rsCapOcrResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Value.
        /// </summary>
        internal static string rsCapOCRValue {
            get {
                return ResourceManager.GetString("rsCapOCRValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string rsCapOff {
            get {
                return ResourceManager.GetString("rsCapOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offhand.
        /// </summary>
        internal static string rsCapOffhand {
            get {
                return ResourceManager.GetString("rsCapOffhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string rsCapOn {
            get {
                return ResourceManager.GetString("rsCapOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string rsCapOverlay {
            get {
                return ResourceManager.GetString("rsCapOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Config.
        /// </summary>
        internal static string rsCapOverlayConfig {
            get {
                return ResourceManager.GetString("rsCapOverlayConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay disabled..
        /// </summary>
        internal static string rsCapOverlayDisabled {
            get {
                return ResourceManager.GetString("rsCapOverlayDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay enabled..
        /// </summary>
        internal static string rsCapOverlayEnabled {
            get {
                return ResourceManager.GetString("rsCapOverlayEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string rsCapOverlayFontSize {
            get {
                return ResourceManager.GetString("rsCapOverlayFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Icon Location.
        /// </summary>
        internal static string rsCapOverlayIconLocation {
            get {
                return ResourceManager.GetString("rsCapOverlayIconLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Update Delay.
        /// </summary>
        internal static string rsCapOverlayUpdateDelay {
            get {
                return ResourceManager.GetString("rsCapOverlayUpdateDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name will overwrite an existing preset..
        /// </summary>
        internal static string rsCapOverwriteWarningPreset {
            get {
                return ResourceManager.GetString("rsCapOverwriteWarningPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants.
        /// </summary>
        internal static string rsCapPants {
            get {
                return ResourceManager.GetString("rsCapPants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Size.
        /// </summary>
        internal static string rsCapParagonBorderSize {
            get {
                return ResourceManager.GetString("rsCapParagonBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon Mode.
        /// </summary>
        internal static string rsCapParagonMode {
            get {
                return ResourceManager.GetString("rsCapParagonMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Size.
        /// </summary>
        internal static string rsCapParagonNodeSize {
            get {
                return ResourceManager.GetString("rsCapParagonNodeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Size (Collapsed).
        /// </summary>
        internal static string rsCapParagonNodeSizeCollapsed {
            get {
                return ResourceManager.GetString("rsCapParagonNodeSizeCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon Node Size (Collapsed):.
        /// </summary>
        internal static string rsCapParagonNodeSizeCollapsedDescription {
            get {
                return ResourceManager.GetString("rsCapParagonNodeSizeCollapsedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon Node Size:.
        /// </summary>
        internal static string rsCapParagonNodeSizeDescription {
            get {
                return ResourceManager.GetString("rsCapParagonNodeSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string rsCapPerformance {
            get {
                return ResourceManager.GetString("rsCapPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string rsCapPolish {
            get {
                return ResourceManager.GetString("rsCapPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string rsCapPortuguese {
            get {
                return ResourceManager.GetString("rsCapPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        internal static string rsCapPositive {
            get {
                return ResourceManager.GetString("rsCapPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string rsCapRanged {
            get {
                return ResourceManager.GetString("rsCapRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string rsCapRenamePreset {
            get {
                return ResourceManager.GetString("rsCapRenamePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution: .
        /// </summary>
        internal static string rsCapResolution {
            get {
                return ResourceManager.GetString("rsCapResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string rsCapRing {
            get {
                return ResourceManager.GetString("rsCapRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string rsCapRogue {
            get {
                return ResourceManager.GetString("rsCapRogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune.
        /// </summary>
        internal static string rsCapRune {
            get {
                return ResourceManager.GetString("rsCapRune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune Detection.
        /// </summary>
        internal static string rsCapRuneDetection {
            get {
                return ResourceManager.GetString("rsCapRuneDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes.
        /// </summary>
        internal static string rsCapRunes {
            get {
                return ResourceManager.GetString("rsCapRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string rsCapRussian {
            get {
                return ResourceManager.GetString("rsCapRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Height (%).
        /// </summary>
        internal static string rsCapScanHeight {
            get {
                return ResourceManager.GetString("rsCapScanHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screencapture Delay.
        /// </summary>
        internal static string rsCapScreenCaptureDelay {
            get {
                return ResourceManager.GetString("rsCapScreenCaptureDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        internal static string rsCapSeasonal {
            get {
                return ResourceManager.GetString("rsCapSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string rsCapSettings {
            get {
                return ResourceManager.GetString("rsCapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Overlay Icon.
        /// </summary>
        internal static string rsCapShowOverlayIcon {
            get {
                return ResourceManager.GetString("rsCapShowOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigils.
        /// </summary>
        internal static string rsCapSigils {
            get {
                return ResourceManager.GetString("rsCapSigils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Affix):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAffix {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Affix location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAffixlocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAffixlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Aspect):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAspect {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Aspect location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdAspectlocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdAspectlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Socket location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdSocketLocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdSocketLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Splitter location):.
        /// </summary>
        internal static string rsCapSimilarityThresholdSplitterLocation {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdSplitterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Tooltip):.
        /// </summary>
        internal static string rsCapSimilarityThresholdTooltip {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Threshold (Type):.
        /// </summary>
        internal static string rsCapSimilarityThresholdType {
            get {
                return ResourceManager.GetString("rsCapSimilarityThresholdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        internal static string rsCapSorcerer {
            get {
                return ResourceManager.GetString("rsCapSorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (EU).
        /// </summary>
        internal static string rsCapSpanishEU {
            get {
                return ResourceManager.GetString("rsCapSpanishEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (LA).
        /// </summary>
        internal static string rsCapSpanishLA {
            get {
                return ResourceManager.GetString("rsCapSpanishLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritborn.
        /// </summary>
        internal static string rsCapSpiritborn {
            get {
                return ResourceManager.GetString("rsCapSpiritborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Overlay.
        /// </summary>
        internal static string rsCapSwitchOverlay {
            get {
                return ResourceManager.GetString("rsCapSwitchOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Preset.
        /// </summary>
        internal static string rsCapSwitchPreset {
            get {
                return ResourceManager.GetString("rsCapSwitchPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System presets:.
        /// </summary>
        internal static string rsCapSystempresets {
            get {
                return ResourceManager.GetString("rsCapSystempresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Screenshot.
        /// </summary>
        internal static string rsCapTakeScreenshot {
            get {
                return ResourceManager.GetString("rsCapTakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempered.
        /// </summary>
        internal static string rsCapTempered {
            get {
                return ResourceManager.GetString("rsCapTempered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempered Affix Detection.
        /// </summary>
        internal static string rsCapTemperedAffixDetection {
            get {
                return ResourceManager.GetString("rsCapTemperedAffixDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string rsCapText {
            get {
                return ResourceManager.GetString("rsCapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Controller.
        /// </summary>
        internal static string rsCapToggleController {
            get {
                return ResourceManager.GetString("rsCapToggleController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: Toggle Lock Screencapture.
        /// </summary>
        internal static string rsCapToggleDebugLockScreencapture {
            get {
                return ResourceManager.GetString("rsCapToggleDebugLockScreencapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Overlay.
        /// </summary>
        internal static string rsCapToggleOverlay {
            get {
                return ResourceManager.GetString("rsCapToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip height (type):.
        /// </summary>
        internal static string rsCapTooltipHeight {
            get {
                return ResourceManager.GetString("rsCapTooltipHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip max height:.
        /// </summary>
        internal static string rsCapTooltipMaxHeight {
            get {
                return ResourceManager.GetString("rsCapTooltipMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip width:.
        /// </summary>
        internal static string rsCapTooltipWidth {
            get {
                return ResourceManager.GetString("rsCapTooltipWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string rsCapTopMost {
            get {
                return ResourceManager.GetString("rsCapTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset (Collapsed).
        /// </summary>
        internal static string rsCapTopOffsetCollapsed {
            get {
                return ResourceManager.GetString("rsCapTopOffsetCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Overlay.
        /// </summary>
        internal static string rsCapTradeOverlay {
            get {
                return ResourceManager.GetString("rsCapTradeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading.
        /// </summary>
        internal static string rsCapTrading {
            get {
                return ResourceManager.GetString("rsCapTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string rsCapTurkish {
            get {
                return ResourceManager.GetString("rsCapTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string rsCapType {
            get {
                return ResourceManager.GetString("rsCapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Detection.
        /// </summary>
        internal static string rsCapUniqueDetection {
            get {
                return ResourceManager.GetString("rsCapUniqueDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniques.
        /// </summary>
        internal static string rsCapUniques {
            get {
                return ResourceManager.GetString("rsCapUniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Collapsed Board.
        /// </summary>
        internal static string rsCapUseCollapsedBoard {
            get {
                return ResourceManager.GetString("rsCapUseCollapsedBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string rsCapWeapon {
            get {
                return ResourceManager.GetString("rsCapWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset {0} activated..
        /// </summary>
        internal static string rsFormatPresetActivated {
            get {
                return ResourceManager.GetString("rsFormatPresetActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Minimized.
        /// </summary>
        internal static string rsLaunchMinimized {
            get {
                return ResourceManager.GetString("rsLaunchMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        internal static string rsMinimizeToTray {
            get {
                return ResourceManager.GetString("rsMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string rsTooltipAdd {
            get {
                return ResourceManager.GetString("rsTooltipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add D4Builds Build.
        /// </summary>
        internal static string rsTooltipAddD4BuildsBuild {
            get {
                return ResourceManager.GetString("rsTooltipAddD4BuildsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maxroll Build.
        /// </summary>
        internal static string rsTooltipAddMaxrollBuild {
            get {
                return ResourceManager.GetString("rsTooltipAddMaxrollBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mobalytics Build..
        /// </summary>
        internal static string rsTooltipAddMobalyticsBuild {
            get {
                return ResourceManager.GetString("rsTooltipAddMobalyticsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add preset.
        /// </summary>
        internal static string rsTooltipAddPreset {
            get {
                return ResourceManager.GetString("rsTooltipAddPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle detection of aspects..
        /// </summary>
        internal static string rsTooltipAspectDetection {
            get {
                return ResourceManager.GetString("rsTooltipAspectDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string rsTooltipBarb {
            get {
                return ResourceManager.GetString("rsTooltipBarb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates at startup..
        /// </summary>
        internal static string rsTooltipCheckforUpdates {
            get {
                return ResourceManager.GetString("rsTooltipCheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to use a controller instead of a mouse. Warning: This method is 70+ ms slower..
        /// </summary>
        internal static string rsTooltipControllerMode {
            get {
                return ResourceManager.GetString("rsTooltipControllerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current item information..
        /// </summary>
        internal static string rsTooltipCurrentItem {
            get {
                return ResourceManager.GetString("rsTooltipCurrentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the build id or url from the D4Builds website and click the add button. The build id is the last part of the url. For example: 660881f7-cb6a-4162-be62-29f0afeb37bf..
        /// </summary>
        internal static string rsTooltipD4BuildsImportHelp {
            get {
                return ResourceManager.GetString("rsTooltipD4BuildsImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit D4Builds.gg.
        /// </summary>
        internal static string rsTooltipD4BuildsWeb {
            get {
                return ResourceManager.GetString("rsTooltipD4BuildsWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test template matching without running Diablo IV..
        /// </summary>
        internal static string rsTooltipDebugMode {
            get {
                return ResourceManager.GetString("rsTooltipDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the debug images for troubleshooting..
        /// </summary>
        internal static string rsTooltipDebugToggle {
            get {
                return ResourceManager.GetString("rsTooltipDebugToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop only.
        /// </summary>
        internal static string rsTooltipDropOnly {
            get {
                return ResourceManager.GetString("rsTooltipDropOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string rsTooltipDruid {
            get {
                return ResourceManager.GetString("rsTooltipDruid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the given tier for a dungeon on the sigil tooltips..
        /// </summary>
        internal static string rsTooltipDungeonTiers {
            get {
                return ResourceManager.GetString("rsTooltipDungeonTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable consumable item type filtering..
        /// </summary>
        internal static string rsTooltipEnableConsumable {
            get {
                return ResourceManager.GetString("rsTooltipEnableConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable seasonal item type filtering..
        /// </summary>
        internal static string rsTooltipEnableSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipEnableSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export debug images as a single image..
        /// </summary>
        internal static string rsTooltipExportDebugImages {
            get {
                return ResourceManager.GetString("rsTooltipExportDebugImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export preset.
        /// </summary>
        internal static string rsTooltipExportPreset {
            get {
                return ResourceManager.GetString("rsTooltipExportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D4 Companion on GitHub.
        /// </summary>
        internal static string rsToolTipGitHub {
            get {
                return ResourceManager.GetString("rsToolTipGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki on GitHub.
        /// </summary>
        internal static string rsToolTipGitHubWiki {
            get {
                return ResourceManager.GetString("rsToolTipGitHubWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import paragon boards..
        /// </summary>
        internal static string rsTooltipImportParagon {
            get {
                return ResourceManager.GetString("rsTooltipImportParagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import preset.
        /// </summary>
        internal static string rsTooltipImportPreset {
            get {
                return ResourceManager.GetString("rsTooltipImportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the import of unique affixes..
        /// </summary>
        internal static string rsTooltipImportUniqueAffixes {
            get {
                return ResourceManager.GetString("rsTooltipImportUniqueAffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active in current season..
        /// </summary>
        internal static string rsTooltipIsSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipIsSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempering available..
        /// </summary>
        internal static string rsTooltipIsTemperingAvailable {
            get {
                return ResourceManager.GetString("rsTooltipIsTemperingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore items with an item power lower than the set limit..
        /// </summary>
        internal static string rsTooltipItemPowerLimit {
            get {
                return ResourceManager.GetString("rsTooltipItemPowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me on Ko-fi.
        /// </summary>
        internal static string rsToolTipKoFi {
            get {
                return ResourceManager.GetString("rsToolTipKoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Minimized..
        /// </summary>
        internal static string rsTooltipLaunchMinimized {
            get {
                return ResourceManager.GetString("rsTooltipLaunchMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset in pixels to set the board in the correct location..
        /// </summary>
        internal static string rsTooltipLeftOffsetCollapsed {
            get {
                return ResourceManager.GetString("rsTooltipLeftOffsetCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the default colors..
        /// </summary>
        internal static string rsTooltipManageColors {
            get {
                return ResourceManager.GetString("rsTooltipManageColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable and change your hotkeys..
        /// </summary>
        internal static string rsTooltipManageHotkeys {
            get {
                return ResourceManager.GetString("rsTooltipManageHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the overlay marker style..
        /// </summary>
        internal static string rsTooltipMarkerStyle {
            get {
                return ResourceManager.GetString("rsTooltipMarkerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the build id or url from the Maxroll website and click the add button. The build id is the last part of the url. For example: t3jx0916.
        /// </summary>
        internal static string rsTooltipMaxrollImportHelp {
            get {
                return ResourceManager.GetString("rsTooltipMaxrollImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Maxroll.com.
        /// </summary>
        internal static string rsTooltipMaxrollWeb {
            get {
                return ResourceManager.GetString("rsTooltipMaxrollWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a base build. Enable checkbox to change current colors..
        /// </summary>
        internal static string rsTooltipMergeBuild1 {
            get {
                return ResourceManager.GetString("rsTooltipMergeBuild1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable checkbox to change colors for duplicated affixes. Otherwise colors from build 1 will be used..
        /// </summary>
        internal static string rsTooltipMergeBuild12 {
            get {
                return ResourceManager.GetString("rsTooltipMergeBuild12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose build to merge. Enable checkbox to change current colors..
        /// </summary>
        internal static string rsTooltipMergeBuild2 {
            get {
                return ResourceManager.GetString("rsTooltipMergeBuild2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables a filter to set a minimal value for affixes..
        /// </summary>
        internal static string rsTooltipMinimalAffixValues {
            get {
                return ResourceManager.GetString("rsTooltipMinimalAffixValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray..
        /// </summary>
        internal static string rsTooltipMinimizeToTray {
            get {
                return ResourceManager.GetString("rsTooltipMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the build url from the Mobalytics website and click the add button..
        /// </summary>
        internal static string rsTooltipMobalyticsImportHelp {
            get {
                return ResourceManager.GetString("rsTooltipMobalyticsImportHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Mobalytics.gg.
        /// </summary>
        internal static string rsTooltipMobalyticsWeb {
            get {
                return ResourceManager.GetString("rsTooltipMobalyticsWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure multi build mode..
        /// </summary>
        internal static string rsTooltipMultiBuildMode {
            get {
                return ResourceManager.GetString("rsTooltipMultiBuildMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer.
        /// </summary>
        internal static string rsTooltipNecro {
            get {
                return ResourceManager.GetString("rsTooltipNecro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings for the ingame overlay..
        /// </summary>
        internal static string rsTooltipOverlayConfig {
            get {
                return ResourceManager.GetString("rsTooltipOverlayConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the font size of overlay notifications..
        /// </summary>
        internal static string rsTooltipOverlayFontSize {
            get {
                return ResourceManager.GetString("rsTooltipOverlayFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the location of the onscreen overlay icon while active..
        /// </summary>
        internal static string rsTooltipOverlayIconLocation {
            get {
                return ResourceManager.GetString("rsTooltipOverlayIconLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in ms between overlay updates. Default 5ms..
        /// </summary>
        internal static string rsTooltipOverlayUpdateDelay {
            get {
                return ResourceManager.GetString("rsTooltipOverlayUpdateDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the border of a paragon node..
        /// </summary>
        internal static string rsTooltipParagonBorderSize {
            get {
                return ResourceManager.GetString("rsTooltipParagonBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the overlay to show paragon boards..
        /// </summary>
        internal static string rsTooltipParagonMode {
            get {
                return ResourceManager.GetString("rsTooltipParagonMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of a single paragon node..
        /// </summary>
        internal static string rsTooltipParagonNodeSize {
            get {
                return ResourceManager.GetString("rsTooltipParagonNodeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of a single paragon node..
        /// </summary>
        internal static string rsTooltipParagonNodeSizeCollapsed {
            get {
                return ResourceManager.GetString("rsTooltipParagonNodeSizeCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful..
        /// </summary>
        internal static string rsTooltipPresetDownloadSuccessful {
            get {
                return ResourceManager.GetString("rsTooltipPresetDownloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the preset matching your configuration and follow the recommended app settings. If the button is disabled turn off the overlay first..
        /// </summary>
        internal static string rsTooltipPresetDownloadTip {
            get {
                return ResourceManager.GetString("rsTooltipPresetDownloadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the system preset images for the tooltip detection..
        /// </summary>
        internal static string rsTooltipRefreshSystemPreset {
            get {
                return ResourceManager.GetString("rsTooltipRefreshSystemPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string rsTooltipRemove {
            get {
                return ResourceManager.GetString("rsTooltipRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove preset.
        /// </summary>
        internal static string rsTooltipRemovePreset {
            get {
                return ResourceManager.GetString("rsTooltipRemovePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename..
        /// </summary>
        internal static string rsTooltipRenamePreset {
            get {
                return ResourceManager.GetString("rsTooltipRenamePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filter values..
        /// </summary>
        internal static string rsTooltipResetMinimalAffixValues {
            get {
                return ResourceManager.GetString("rsTooltipResetMinimalAffixValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string rsTooltipRogue {
            get {
                return ResourceManager.GetString("rsTooltipRogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune of Ritual.
        /// </summary>
        internal static string rsTooltipRuneCondition {
            get {
                return ResourceManager.GetString("rsTooltipRuneCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle detection of runes..
        /// </summary>
        internal static string rsTooltipRuneDetection {
            get {
                return ResourceManager.GetString("rsTooltipRuneDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune of Invocation.
        /// </summary>
        internal static string rsTooltipRuneEffect {
            get {
                return ResourceManager.GetString("rsTooltipRuneEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of screen to scan for item tooltip..
        /// </summary>
        internal static string rsTooltipScanHeight {
            get {
                return ResourceManager.GetString("rsTooltipScanHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in ms between screencaptures. Default 50ms..
        /// </summary>
        internal static string rsTooltipScreenCaptureDelay {
            get {
                return ResourceManager.GetString("rsTooltipScreenCaptureDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal.
        /// </summary>
        internal static string rsTooltipSeasonal {
            get {
                return ResourceManager.GetString("rsTooltipSeasonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set affix.
        /// </summary>
        internal static string rsTooltipSetAffix {
            get {
                return ResourceManager.GetString("rsTooltipSetAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set aspect.
        /// </summary>
        internal static string rsTooltipSetAspect {
            get {
                return ResourceManager.GetString("rsTooltipSetAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set controller images..
        /// </summary>
        internal static string rsTooltipSetControllerImages {
            get {
                return ResourceManager.GetString("rsTooltipSetControllerImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Rune.
        /// </summary>
        internal static string rsTooltipSetRune {
            get {
                return ResourceManager.GetString("rsTooltipSetRune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set sigil.
        /// </summary>
        internal static string rsTooltipSetSigil {
            get {
                return ResourceManager.GetString("rsTooltipSetSigil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Unique.
        /// </summary>
        internal static string rsTooltipSetUnique {
            get {
                return ResourceManager.GetString("rsTooltipSetUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show overlay icon when the overlay is active..
        /// </summary>
        internal static string rsTooltipShowOverlayIcon {
            get {
                return ResourceManager.GetString("rsTooltipShowOverlayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a blacklist allows you to add all sigil affixes you do not want..
        /// </summary>
        internal static string rsTooltipSigilModes {
            get {
                return ResourceManager.GetString("rsTooltipSigilModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorceress.
        /// </summary>
        internal static string rsTooltipSorc {
            get {
                return ResourceManager.GetString("rsTooltipSorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritborn.
        /// </summary>
        internal static string rsTooltipSpiritborn {
            get {
                return ResourceManager.GetString("rsTooltipSpiritborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between the affix and paragon overlay..
        /// </summary>
        internal static string rsTooltipSwitchOverlay {
            get {
                return ResourceManager.GetString("rsTooltipSwitchOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle through available affix presets..
        /// </summary>
        internal static string rsTooltipSwitchPreset {
            get {
                return ResourceManager.GetString("rsTooltipSwitchPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot..
        /// </summary>
        internal static string rsTooltipTakeScreenshot {
            get {
                return ResourceManager.GetString("rsTooltipTakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle detection of tempered affixes..
        /// </summary>
        internal static string rsTooltipTemperedAffixDetection {
            get {
                return ResourceManager.GetString("rsTooltipTemperedAffixDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the controller mode on/off..
        /// </summary>
        internal static string rsTooltipToggleController {
            get {
                return ResourceManager.GetString("rsTooltipToggleController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks the latest screencapture as the default input image..
        /// </summary>
        internal static string rsTooltipToggleDebugLockScreencapture {
            get {
                return ResourceManager.GetString("rsTooltipToggleDebugLockScreencapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the overlay on/off..
        /// </summary>
        internal static string rsTooltipToggleOverlay {
            get {
                return ResourceManager.GetString("rsTooltipToggleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the in-game overlay.
        /// </summary>
        internal static string rsTooltipToggleOverlayOff {
            get {
                return ResourceManager.GetString("rsTooltipToggleOverlayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled the in-game overlay.
        /// </summary>
        internal static string rsTooltipToggleOverlayOn {
            get {
                return ResourceManager.GetString("rsTooltipToggleOverlayOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Diablo IV Companion the top most window..
        /// </summary>
        internal static string rsTooltipTopMost {
            get {
                return ResourceManager.GetString("rsTooltipTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset in pixels to set the board in the correct location..
        /// </summary>
        internal static string rsTooltipTopOffsetCollapsed {
            get {
                return ResourceManager.GetString("rsTooltipTopOffsetCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows trade values for items..
        /// </summary>
        internal static string rsTooltipTradeOverlay {
            get {
                return ResourceManager.GetString("rsTooltipTradeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle detection of unique items..
        /// </summary>
        internal static string rsTooltipUniqueDetection {
            get {
                return ResourceManager.GetString("rsTooltipUniqueDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string rsTooltipUpdate {
            get {
                return ResourceManager.GetString("rsTooltipUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the smaller collapsed paragon board..
        /// </summary>
        internal static string rsTooltipUseCollapsedBoard {
            get {
                return ResourceManager.GetString("rsTooltipUseCollapsedBoard", resourceCulture);
            }
        }
    }
}
